In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import matplotlib.cm as cm
import qutip as qu
import sympy as sym

In [3]:
g10, δ, Δ = sym.symbols("g_{10}, δ, Δ")

In [4]:
H1 = sym.Matrix([[0, g10, 0],
                 [g10, -Δ, 0],
                 [0, 0, δ]])
H1

Matrix([
[     0, g_{10}, 0],
[g_{10},     -Δ, 0],
[     0,      0, δ]])

In [5]:
H1.eigenvects()

[(δ,
  1,
  [Matrix([
   [0],
   [0],
   [1]])]),
 (-Δ/2 - sqrt(4*g_{10}**2 + Δ**2)/2,
  1,
  [Matrix([
   [Δ/g_{10} + (-Δ/2 - sqrt(4*g_{10}**2 + Δ**2)/2)/g_{10}],
   [                                                    1],
   [                                                    0]])]),
 (-Δ/2 + sqrt(4*g_{10}**2 + Δ**2)/2,
  1,
  [Matrix([
   [Δ/g_{10} + (-Δ/2 + sqrt(4*g_{10}**2 + Δ**2)/2)/g_{10}],
   [                                                    1],
   [                                                    0]])])]

In [7]:
g1 = 10
g2 = 1
ω = 5 + 1j*2
ω /= np.abs(ω)
d = 1

In [8]:
a = qu.destroy(2)
Ha = ω * a.dag() * a
Hb = d * a.dag() * a

In [10]:
Ha.eigenstates()

(array([0.        +0.j        , 0.92847669+0.37139068j]),
 array([Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
        Qobj data =
        [[1.]
         [0.]]                                                                ,
        Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.]
         [1.]]                                                                ],
       dtype=object))