In [1]:
import numpy as np
import qutip as qu

In [2]:
σ10 = qu.Qobj([[0, 1, 0],
               [0, 0, 0],
               [0, 0, 0]])
σ21 = qu.Qobj([[0, 0, 0],
               [0, 0, 1],
               [0, 0, 0]])

In [3]:
σ10.dag() * σ10 * σ21 - σ21 * σ10.dag() * σ10

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

In [4]:
σ21.dag() * σ21 * σ21 - σ21 * σ21.dag() * σ21

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]

In [5]:
σ21 * σ21.dag() - σ21.dag() * σ21

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]

In [6]:
σ10.dag()*σ10 - σ10*σ10.dag()

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]